// Code generated by hertz generator.

package main

import (
	"doing_now/be/biz/config"
	"doing_now/be/biz/db"
	"doing_now/be/biz/middleware"
	"doing_now/be/biz/util/logger"
	_ "doing_now/be/docs"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/protocol"
	"github.com/go-playground/validator/v10"
	"github.com/hertz-contrib/swagger"
	swaggerFiles "github.com/swaggo/files"
)

// @title			Doing Now
// @version		1.0
// @description	doing now
// @BasePath		/
// @schemes		http
func main() {
	config.Init("./conf/deploy.local.yml")
	logger.Init()
	db.Init()

	h := NewEngine()

	// swagger文档地址
	h.GET("/swagger/*any", swagger.WrapHandler(swaggerFiles.Handler))

	h.Spin()
}

func NewEngine() *server.Hertz {
	vd := validator.New(validator.WithRequiredStructEnabled())

	h := server.Default(
		server.WithHostPorts("0.0.0.0:8000"),
		server.WithCustomValidatorFunc(func(_ *protocol.Request, req any) error {
			return vd.Struct(req)
		}),
	)
	h.Use(middleware.Suite()...)

	register(h)

	return h
}
