// Code generated by hertz generator.

package main

import (
	handler "doing_now/be/biz/handler"
	"doing_now/be/biz/middleware/jwt"
	"doing_now/be/biz/middleware/ratelimit"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	api := r.Group("/api/v1")
	{
		user := api.Group("/user")
		{
			user.POST("/register", ratelimit.NewRegisterProtection(), handler.Register)
			user.POST("/login", ratelimit.NewLoginProtection(), handler.Login)
			user.POST("/refresh_token", handler.RefreshToken)
			loginUser := user.Group("/", jwt.ValidateMW())
			{
				loginUser.POST("/logout", handler.Logout)
				loginUser.GET("/info", handler.GetUserInfo)
				loginUser.POST("/update_info", handler.UpdateInfo)
				loginUser.POST("/update_password", handler.UpdatePassword)
			}
		}
	}
}
